# Generated by Django 3.1.7 on 2021-04-18 15:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.now)),
                ('category', models.CharField(choices=[('PP', 'Protein Powder'), ('PW', 'Pre Workout'), ('CR', 'Creatine'), ('MG', 'Mass Gainers'), ('BS', 'Bars & Snacks'), ('VI', 'Vitamins')], max_length=200)),
                ('in_stock', models.IntegerField(default=100000)),
                ('available', models.BooleanField(blank=True, default=False, null=True)),
            ],
        ),
    ]
