# Generated by Django 3.1.7 on 2021-04-18 15:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='date_posted',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
