# Generated by Django 3.1.7 on 2021-04-27 22:12

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_auto_20210420_2048'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='details',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
