# Generated by Django 3.1.7 on 2021-05-19 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_customer'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
